sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
services: mysql
before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
before_script:
  - npm install -g grunt-cli
